### ISSUE TITLE
Change messages?

### ISSUE THREAD

**Issue by dan-nkl** [SuperPyroManiac/GPRealEstate#7]
Hey, it's not possible to change the messages of the plugin at the moment?
Maybe adding a file with all the strings?

**Comment by SuperPyroManiac** [comment]
I'll work on a language file.

**Comment by SuperPyroManiac** [comment]
Due to being busy real life, and lack of interest in Minecraft, this is something I do not plan to add. It's simple but would take a while to move everything. I will keep the plugin up to date and make sure all current features work, but have no plans to add anything, others can feel free to do it and I can merge the code.
